site_name: MXNet.jl
site_author: pluskid
repo_url: https://github.com/dmlc/MXNet.jl
theme: readthedocs
pages:
  - Home: index.md
  - API Documentation:
    - 'ndarray': 'api/ndarray.md'
    - 'symbol': 'api/symbol.md'
